import { useNavigate } from "react-router-dom";
import { motion } from "framer-motion";
import { ChevronRight, ShieldCheck, Leaf, Search, Sliders, AlertCircle, UsersRound } from "lucide-react";
import SkinFooter from "@/components/SkinFooter";

const sections = [
  {
    icon: Search,
    title: "Searching Products",
    desc: "Use the search bar to find any skincare product by name or brand. Results appear instantly as you type.",
  },
  {
    icon: ShieldCheck,
    title: "Safety Score",
    desc: "Each product is scored from 0–10 based on ingredient safety analysis. Scores above 8.5 are considered excellent.",
  },
  {
    icon: Leaf,
    title: "Eco Score",
    desc: "The eco score reflects the environmental impact of a product's ingredients, packaging, and manufacturing process.",
  },
  {
    icon: Sliders,
    title: "Using Filters",
    desc: "Filter products by ingredients (include/exclude), minimum safety or eco score, and company. Combine filters for precise results.",
  },
  {
    icon: AlertCircle,
    title: "Disclaimer",
    desc: "All scores are generated by AI models and should be used as a guide, not medical advice. Always consult a dermatologist for skin concerns.",
  },
  {
    icon: UsersRound,
    title: "Developers",
    desc: (
      <div className="flex flex-wrap gap-2 mt-1">
        {["Vikram Bhide", "Aryan Unhale", "Isha Kamthe", "Atharva Vhora", "Pranjal Kute"].map((name) => (
          <span key={name} className="px-3 py-1 rounded-full bg-primary/10 text-sm text-foreground font-medium">
            {name}
          </span>
        ))}
      </div>
    ),
  },
];

const Help = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="max-w-3xl mx-auto pt-24 px-4 md:px-6 pb-12">
        <button
          onClick={() => navigate("/")}
          className="mb-8 text-muted-foreground hover:text-foreground flex items-center gap-2 skin-transition text-sm font-medium"
        >
          <ChevronRight className="rotate-180" size={18} /> Back to home
        </button>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
        >
          <h1 className="text-4xl font-bold mb-2">Help Center</h1>
          <p className="text-muted-foreground mb-12">Everything you need to know about SkinAura.</p>

          <div className="space-y-4">
            {sections.map((s, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.08 * i }}
                className="card-skin p-6 flex gap-5"
              >
                <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center shrink-0">
                  <s.icon size={20} className="text-primary" />
                </div>
                <div>
                  <h3 className="font-bold mb-1">{s.title}</h3>
                  <div className="text-sm text-muted-foreground leading-relaxed">{s.desc}</div>
                </div>
              </motion.div>
            ))}
          </div>
        </motion.div>
      </div>
      <SkinFooter />
    </div>
  );
};

export default Help;
