import { AlertCircle } from "lucide-react";

const SkinFooter = () =>
<footer className="py-12 text-center text-muted-foreground text-sm mt-24">
    <div className="flex items-center justify-center gap-2 mb-2">
      <AlertCircle size={14} />
      <p>All scores are generated by AI. Use with caution.</p>
    </div>
    <p>© 2025 SkinAura. All rights reserved.</p>
  </footer>;


export default SkinFooter;